spring.application.name=SafeRoute

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:postgres.hsdyxyhvpjmkqmhgbmfo}
spring.datasource.password=${DATABASE_PASSWORD:Qusnyb-muxhu0-cejgob}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
